In [1]:
v = [0.5, 0.75, 1., 1.5, 2.]

In [4]:
# Populate any dimension of array wanted with other arrays
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [7]:
# Row
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [6]:
m[1][1]

0.75

In [10]:
# but this is very very very limited - try selecting a column! so enter numpy
import numpy as np
a = np.array([0, 0.5, 1., 1.5, 2.])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
type(a)

numpy.ndarray

In [15]:
a = np.array(['A', 'B', 'C'])
a

array(['A', 'B', 'C'], dtype='<U1')

In [18]:
# start inclusive, end exclusive, skip #
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
a = np.arange(2, 30, 2, dtype=np.float)
a

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28.])

In [20]:
a[5:]

array([12., 14., 16., 18., 20., 22., 24., 26., 28.])

In [22]:
a[:5]

array([ 2.,  4.,  6.,  8., 10.])

In [23]:
a.sum()

210.0

In [24]:
a.std()

8.06225774829855

In [25]:
a.cumsum()

array([  2.,   6.,  12.,  20.,  30.,  42.,  56.,  72.,  90., 110., 132.,
       156., 182., 210.])

In [29]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [31]:
a**2

array([  4.,  16.,  36.,  64., 100., 144., 196., 256., 324., 400., 484.,
       576., 676., 784.])

In [32]:
a ** a

array([4.00000000e+00, 2.56000000e+02, 4.66560000e+04, 1.67772160e+07,
       1.00000000e+10, 8.91610045e+12, 1.11120068e+16, 1.84467441e+19,
       3.93464081e+22, 1.04857600e+26, 3.41427877e+29, 1.33373578e+33,
       6.15611958e+36, 3.31455231e+40])

In [34]:
# element-wise exponential function
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07, 4.85165195e+08, 3.58491285e+09, 2.64891221e+10,
       1.95729609e+11, 1.44625706e+12])

In [35]:
# element-wise square root
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
       4.69041576, 4.89897949, 5.09901951, 5.29150262])

In [39]:
b = np.array([a, a*2])
b

array([[ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
        28.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48., 52.,
        56.]])

In [40]:
b[0]

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28.])

In [41]:
b[0, 2]

6.0

In [43]:
b[:, 1]

array([4., 8.])

In [44]:
b.sum()

630.0

In [45]:
b.sum(axis=0)

array([ 6., 12., 18., 24., 30., 36., 42., 48., 54., 60., 66., 72., 78.,
       84.])

In [46]:
b.sum(axis=1)

array([210., 420.])

In [49]:
c = np.zeros((2,3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [51]:
c = np.ones((2,3,4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [53]:
# order can be c (C-like which is row wise) or f (Fortran-like which is column wise)
d= np.zeros_like(c, dtype='f16', order='c')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [54]:
e = np.empty((2,3,2))
e

array([[[2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314]],

       [[2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314]]])

In [56]:
f = np.empty_like(c)
f

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [57]:
# eye is a diagonal matrix for some reason?
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
# evenly spaced n (3rd argument) elements between x (1st argument) and y (2nd argument)
g = np.linspace(5, 15, 12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [67]:
# metadata are stored as props, not methods
g.size # num elements in numpy array

12

In [63]:
g.itemsize

8

In [66]:
g.ndim # num array dimensions

1

In [68]:
g.dtype # numpy internal datatype

dtype('float64')

In [70]:
g.nbytes # size in bytes

96

In [72]:
'''
reshaping vs. resizing
---------
Reshaping provides a VIEW on the underlying data - it has to add up to same number of elements 
Resizing creates a new np.array (though it is temp)
''' 
g.reshape((4, 3))

array([[ 5.        ,  5.90909091,  6.81818182],
       [ 7.72727273,  8.63636364,  9.54545455],
       [10.45454545, 11.36363636, 12.27272727],
       [13.18181818, 14.09090909, 15.        ]])

In [73]:
g.reshape((3, 4))

array([[ 5.        ,  5.90909091,  6.81818182,  7.72727273],
       [ 8.63636364,  9.54545455, 10.45454545, 11.36363636],
       [12.27272727, 13.18181818, 14.09090909, 15.        ]])

In [76]:
h = g.reshape((6, 2))
h

array([[ 5.        ,  5.90909091],
       [ 6.81818182,  7.72727273],
       [ 8.63636364,  9.54545455],
       [10.45454545, 11.36363636],
       [12.27272727, 13.18181818],
       [14.09090909, 15.        ]])

In [81]:
h.T # transpose
h.transpose() # same

array([[ 5.        ,  6.81818182,  8.63636364, 10.45454545, 12.27272727,
        14.09090909],
       [ 5.90909091,  7.72727273,  9.54545455, 11.36363636, 13.18181818,
        15.        ]])

In [107]:
g1 = np.linspace(1, 10, 10)
g2 = g1.reshape((2,5))
g2

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [101]:
np.resize(g2, (3,1)) # resize first arg to RC shape tuple second arg

array([[1.],
       [2.],
       [3.]])

In [102]:
np.resize(g2, (1,5))

array([[1., 2., 3., 4., 5.]])

In [103]:
# stacking lets you stack multiple ndarrays horizontally or vertically
np.hstack((g2, g2 *2))

array([[ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.],
       [ 6.,  7.,  8.,  9., 10., 12., 14., 16., 18., 20.]])

In [104]:
np.vstack((g2, g2 * 0.5))

array([[ 1. ,  2. ,  3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ,  9. , 10. ],
       [ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ]])

In [105]:
# the opposite of this is flattening arrays either column wise or row wise
g2.flatten(order='C')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
g2.flatten(order='F')

array([ 1.,  6.,  2.,  7.,  3.,  8.,  4.,  9.,  5., 10.])

In [108]:
# generate boolean expression over array
g2 % 3 == 0

array([[False, False,  True, False, False],
       [ True, False, False,  True, False]])

In [119]:
# can also generate another array from this
g2[g2 % 2 == 0] # i.e. all evens

array([ 2.,  4.,  6.,  8., 10.])

In [120]:
# this is extended to np.where which lets you set values for True and False
np.where(g2 % 2 == 0, 'Yum', 'Yuck')

array([['Yuck', 'Yum', 'Yuck', 'Yum', 'Yuck'],
       ['Yum', 'Yuck', 'Yum', 'Yuck', 'Yum']], dtype='<U4')

In [121]:
# literally always use numpy it is way way way faster than python arrays

In [123]:
# structured arrays are the equivalent of a schema - you can have a different dtype per column
# Set this up as an array of two args tuples (three for arrays)
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [124]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [128]:
# instantiate
s = np.array([('Smith', 45, 1.83, (0,1)),
             ('Jones', 53, 1.72, (2,2))], dtype=dt)
s # kinda a lot of typing and hard to reason about in a constructor - but fine if ETL'ing

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [130]:
s['Name'] # pandas style look ups

array([b'Smith', b'Jones'], dtype='|S10')

In [131]:
s['Age']

array([45, 53], dtype=int32)

In [132]:
s['Children/Pets']

array([[0, 1],
       [2, 2]], dtype=int32)

In [133]:
s[0]

(b'Smith', 45, 1.83, [0, 1])

In [135]:
s[0]['Name']

b'Smith'

In [136]:
# Vectorization - the real real power of numpy

In [137]:
np.random.seed(100)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3)) * 0.5

In [138]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [139]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [140]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [141]:
# broadcasting - scalar operations without needing to match matrix shapes
s * 2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [142]:
(r+s)/2

array([[0.  , 0.75, 1.5 ],
       [2.25, 3.  , 3.75],
       [4.5 , 5.25, 6.  ],
       [6.75, 7.5 , 8.25]])